### ISSUE TITLE
Project won't start

### ISSUE THREAD

**Issue by rBok6** [Maclinz/yt_animated-landing-page#1]
Hello! I need a little help starting the project. How can I solve this error?

![IMG_20220418_170829.jpg](https://user-images.githubusercontent.com/13161094/163878448-79feff13-c404-4ee7-9b1c-1b783ccc0691.jpg)

**Comment by sajibhn** [comment]
did you run " npm install " before starting the project?

**Comment by rBok6** [comment]
> did you run " npm install " before starting the project?  

Yes, then I got an error saying the project was build with an older version of node, so I tried downgrading to an older version and that led to a lot of deprecated dependencies errors. I didn't keep trying with this. But thanks for your reply anyways.

**Comment by rBok6** [comment]
So an easy solution that I found for this was to manually edit the package-lock.json file and change the version number from 1 to 2. And that worked to install all the dependencies and to start the project.
